### ISSUE TITLE
How to multiply the hashed tweak of a public key by the generator G?

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#12]
This is, what I believe, is the last niggling part of this whole process that has been befuddling me.

I can successfully hash_hmac(ParentKey||ChildIndex,ParentChainCode) to get a valid hash that I can split into two sections, the left site is the tweak(the public key offset of the ParentKey), and the right is the ChildChainCode.

The next step in the process is to multiply the tweak by the generator point G to obtain the ChildPublicKey.

Once I have that, it's simply a matter of adding the result of tweak*G to the ParentPublicKey and I'll have the change-level public key and chaincode, which can then be used to create payment addresses using the PublicKey||Index and ChainCode with the same hash as above and then process those results, which eventually results in a public key that can be converted to a payment address.

If you, or someone you know, knows how to write this portion of the code using PHP7, I'm willing to provide a reward in BTC.

**Comment by Septem151** [comment]
I’ll take a crack at it. Would you mind sharing with me the libraries/code you are using and have so far? Easiest way would be through email unless it’s already within this github repo.

**Comment by EAWF** [comment]
Hi Carson!  Thanks for responding!

I've just been working on my server, but here's a copy of what I've been 
working with.

For testing, I am using the mnemonic "abandon abandon abandon abandon 
abandon abandon abandon abandon abandon abandon abandon about" plugged 
into Ian Coleman's BIP39 online utility located at: 
https://iancoleman.io/bip39/ and using the BIP49 tab that calculates a 
set of test vectors for proof of concept/computation.

The exported ypub is found at the Account Extended Public Key field, and 
corresponds correctly from a working Mycelium HD Wallet's Exported 
Account-Level Extended Public Key.  In other words, I plugged the above 
mnemonic into a fresh install of Mycelium, and got the same exported, 
extended, account-level ypub via the wallet, so I know that it works and 
my data should be on the right track.

I'm using and installation of PHP 7.4 with the php-mcrypt, php-base58, 
and php-gmp extensions installed.

Remember, I'm trying to do this all WITHOUT libraries at all...just pure 
PHP.

Here's the code I'm using:
<?php
   $pub = 
"ypub6Ww3ibxVfGzLrAH1PNcjyAWenMTbbAosGNB6VvmSEgytSER9azLDWCxoJwW7Ke7icmizBMXrzBx9979FfaHxHcrArf3zbeJJJUZPf663zsP";
   $data = bin2hex(base58_decode($pub));
   $payload = substr($data,0,-8);
   $sum = substr($data,-8);
   $comp = 
substr(hash('sha256',hex2bin(hash('sha256',hex2bin($payload)))),0,8);
   if ($sum !== $comp){echo "ERROR: Checksum Mismatch.\n";exit;}
   $ParentType = substr($payload,0,8);
   $ParentDepth = substr($payload,8,2);
   $ParentFingerprint = substr($payload,10,8);
   $ParentAccountIndex = substr($payload,18,8);
   $ParentChainCode = substr($payload,26,64);  // input for "secret" of 
hash_hmac below
   $ParentPublicKey = substr($payload,90,66);

   // Start Deriving Change Level Public Key and Chain Code:
   $Index = "0"; // we want change level derivation for this iteration.  
If we wanted change addresses derived, we would use "1".
   $hmac = 
hash_hmac("sha512",pack("H*",$ParentPublicKey).pack("H*",$Index),pack("H*",$ParentChainCode));
   $tweak = substr($hmac,0,64);
   $ChildChainCode = substr($hmac,-64);  // store to use for next 
hash_hmac iteration for Payment Address Derivation.

   // The next is an attempt from information found at the bottom of:  
https://bitcoin.stackexchange.com/questions/62533/key-derivation-in-hd-wallets-using-the-extended-private-key-vs-hardened-derivati
   $offset = strrev(gmp_strval(gmp_init($offset,16),2));
   for ($x = 0; $x < strlen($offset); $x++){
    if($offset[$x] === "1"){
     $tweak = gmp_add($tweak,gmp_pow(2,$x));
    }
   }
   // I get what seems to be a valid tweak, but I just don't get how to 
to the double and add procedure within php and gmp.

   // Here's where I'm stuck, and here's the psuedocode for what needs to 
happen:
   // $tweakG = $tweak * G;   // probably requires gmp
   // $ChildPublicKey = $ParentPublicKey + $tweakG;  // probably requires 
gmp also

   // Once we have this, we start the above derivation process again, 
except with:
   $Index = "[desired payment address index]"; // this is the payment 
address derivation for this iteration.
   $hmac = 
hash_hmac("sha512",pack("H*",$ChildPublicKey).pack("H*",$Index),pack("H*",$ChildChainCode));
   $tweak = substr($hmac,0,64);
   $ChildChainCode = substr($hmac,-64);  // now needed only to determine 
even/odd so as to prepend 02, or 03 to the ChildPublicKey

   // $tweakG = $tweak * G;   // probably requires gmp
   // $ChildPublicKey = $ParentPublicKey + $tweakG;  // probably requires 
gmp also

   // then we just process normally to create a payment address from the 
public key, and we should be able to match the payment addresses listed 
at the bottom of https://iancoleman.io/bip39/ .
?>

THEN, this same system SHOULD be able to work for BIP44 and BIP84 
addresses too.


Some of the rabbit-holes I've been traveling down:

https://www.reddit.com/r/Bitcoin/comments/9922jj/how_in_bitcoin_to_generate_a_public_key_from_a/

https://learnmeabitcoin.com/technical/extended-keys (look down near the 
bottom for some php code, but it requires the bitwasp library)

https://github.com/BitcoinPHP/BitcoinECDSA.php/blob/master/src/BitcoinPHP/BitcoinECDSA/BitcoinECDSA.php 
// this looks promising.

https://bitcoin.stackexchange.com/questions/62533/key-derivation-in-hd-wallets-using-the-extended-private-key-vs-hardened-derivati

**Comment by Septem151** [comment]
```php
$offset = strrev(gmp_strval(gmp_init($offset,16),2));
for ($x = 0; $x < strlen($offset); $x++){
    if($offset[$x] === "1"){
        $tweak = gmp_add($tweak,gmp_pow(2,$x));
    }
}
```

Am I missing something here? `$offset` isn't defined anywhere else and when I try to run this code I'm getting an error at the first line of this section. The error is: 

> Warning: gmp_init(): Unable to convert variable to GMP - wrong type

Is `$offset` being defined elsewhere in your code?

**Comment by Septem151** [comment]
I've finished creating a PHP script that can successfully create extended public keys for all types (xpub, ypub, zpub). However, only addresses can be retrieved from xpub and ypub, as we've yet to find a suitable library, code snippets, or extension for Bech32 encoding.

I must say, that BitcoinECDSA github repository **REALLY** helped! I appreciated how simple it was to integrate into a solution without being overly complex. I've integrated only the functions that are necessary. Since the script is rather long, I'm going to link you to a [PasteBin](https://pastebin.com/zTpDnjhb) instead.

At the top of the script, there are some tests for both xpub and ypub. Beginning at line 96 is where the actual script happens. A good starting place to look at would be on line 577, where a function called `CKDpub` takes a parent extended public key and derives a child extended public key. Line 595 and 596 is where the tweak is scalar multiplied and then added to the parent public key. I suggest that you backtrack from lines 595 and 596 and that should give you a good picture of what is happening when performing scalar multiplication and addition.

**Comment by EAWF** [comment]
Carson,

WOW!!  You're awesome!  Thanks for the PasteBin code.

That's a lot of coding done quickly. Far beyond even my best days 
programming!
Do you realize that I've been bashing my head against the wall trying to 
do this for the last 3 years?

I found this at: https://bitcointalk.org/index.php?topic=4992632.0

I cut and pasted the text from the forum as I wasn't sure if you had an 
account on bitcointalk or not.

I'm not sure what #4 and #8 are, but the references are located at the 
bottom of this text.

Bob

===================================================================================================
FROM: https://bitcointalk.org/index.php?topic=4992632.0  (Step by step 
guide to go from public key to a Bech32 encoded address)
===================================================================================================

Bitcoin wiki has a pretty good step-by-step explanation of how to go 
from a public key to a base58_encoded address which contains the values 
for each step of the way[1]. But unfortunately I could not find anything 
similar for Bech32_encoding. Additionally I found the reference 
implementations a bit confusing[2]! The information is out there[3] but 
I feel like having it step-by-step like "[1]" can make it a lot easier 
specially for developers. For example during unit testing I was getting 
a different address (bc1qp63uahgrxged4z5jswyt5dn5v3lzsem6c0qqhg8) for 
below public key and I wasn't sure where the bug was coming from, this 
visualization helped me [4] realize I was appending the version byte 
before converting the bits instead of after. So hopefully these steps 
can help someone like me looking for them.

How to create a Bech32 address from a public key:

1 - Get a compressed[5] public key (0x02 or 0x03 followed by 32 byte X 
coordinate):
     0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798

2 - Perform SHA-256 hashing on the public key:
     0f715baf5d4c2ed329785cef29e562f73488c8a2bb9dbc5700b361d54b9b0554

3 - Perform RIPEMD-160 hashing on the result of SHA-256:
     751e76e8199196d454941c45d1b3a323f1433bd6

4 - The result of step 3 is an array of 8-bit unsigned integers (base 
2^8=256) and Bech32 encoding converts this to an array of 5-bit unsigned 
integers (base 2^5=32) so we "squash" the bytes to get:
     hex:     
0e140f070d1a001912060b0d081504140311021de14030c1d03040f1814060e1e16 or
     numbers: 14 20 15 07 13 26 00 25 18 06 11 13 08 21 04 20 03 17 02 29 
03 12 29 03 04 15 24 20 06 14 30 22 or
     binary:  01110 10100 01111 00111 01101 11010 00000 11001 10010 00110 
01011 01101 01000 10101 00100 10100 00011 10001 00010 11101 00011 01100 
11101 00011 00100 01111 11000 10100 00110 01110 11110 10110

5 - Add the witness version byte in front of the step 4 result (current 
version is 0):
     000e140f070d1a001912060b0d081504140311021d030c1d03040f1814060e1e16

6 - Compute the checksum by using the data from step 5 and the H.R.P (bc 
for MainNet and tb for TestNet)
     0c0709110b15

7 - Append the checksum to result of step 5 (we now have an array of 
5-bit integers):
     
000e140f070d1a001912060b0d081504140311021d030c1d03040f1814060e1e160c0709110b15

8 - Map each value to its corresponding character in Bech32Chars 
(qpzry9x8gf2tvdw0s3jn54khce6mua7l) 00 -> q, 0e -> w,...
     qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4

9 - A Bech32_encoded address consists of 3 parts: HRP + Separator + 
Data:
     bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4

The final result from step 9 is the same as example in BIP-173[6]

References:
[1] 
https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses
[2] https://github.com/sipa/bech32
[3] https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
[4] https://en.bitcoin.it/w/images/en/4/48/Address_map.jpg
[5] Only compressed public keys are allowed: 
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#restrictions-on-public-key-type
[6] 
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#examples

===================================================================================================

**Comment by Septem151** [comment]
Bech32 support has been added. [New PasteBin Link](https://pastebin.com/xQ15TwxV)

I basically took the python code from the [BIP-173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32) proposal and converted it into PHP code, which took care of the checksum (the hardest part). The process of determining the checksum is very efficient. The conversion of public key's hash into the bech32 characters, however, is probably a lot slower than it could be. I had to use a lot of gmp functions since my understanding of bitshift operations isn't the best. I'm sure it could be done a lot more efficiently/faster, but it does work now.

**Comment by EAWF** [comment]
Again, awesome job!

RE: the derivation path printout in the test.
I noticed that you're not using the actual account number(child number 
of the account level) for the printout.  You may want to use Ian's page, 
change the account numbers for extended public key's 2, and 3, and pull 
those vectors in for testing.  We have no idea which account someone is 
going to use, and it's a really good idea to provide the correct path 
for each address derived.

RE: spelling bug in the test for zpubs, you missed an xpub reference.
not a biggie.

RE: Git Repository
I'm thinking that now that the solution is entirely different to the 
original repo, maybe the current repo should be shut down or trashed. 
I've created a currently private repo named getBTC as a replacement, but 
wanted to get your thoughts on what to do with what you've created?

**Comment by PeterNSteinmetz** [comment]
Bob, normally just do a major release when there are major changes. No need to wait switch repositories. Or you can do a major branch.

**Comment by EAWF** [comment]
> Bob, normally just do a major release when there are major changes. No need to switch repositories. Or you can do a major branch.

And if I want to do a repo name change?  Do I just change the name, or do I need to branch?

**Comment by Septem151** [comment]
> And if I want to do a repo name change? Do I just change the name, or do I need to branch?

You can always change the name of the repo. The only change is that old links to the repository will reach a 404 page as they will be linking to a non-existent repo name. You have a few options with a new branch.

If you wish to keep all of your previous commit history:
* `git checkout -b old-master` - creates a new branch for the current state of the repo to go into
* `git push -u origin old-master` - push the newly created branch to GitHub
* `git push checkout master` - checkout the master branch
* make any changes you want, such as deleting all files, etc. When finished with changes:
* `git add .` - stage all of your changes
* `git commit -m "some commit message here"` - commit your changes
* `git push -u origin master` - push your new commit to master with the cleaned codebase

I recommend this route as it allows those that have forked the repository to pull in the changes, rather than getting conflicts by simply deleting the .git folder and re-writing your commit history with a --force push. In addition, the old master branch will retain the state of how the repository was when this change occurred, in case you need to go through it and pull out files you want to keep. Eventually when you are done with the old master branch you can simply delete it:
* `git push -d origin old-master` - deletes the old master branch from Github
* `git branch -d old-master` - deletes the old master branch from your local Git repository

**Comment by Septem151** [comment]
@EAWF Wouldn't it be better to keep this repo since it has Stars + Watchers already, and therefore a better reputation? It would be very simply to port over what we have on the other repo into this one. Instructions on how to do so are in the comment above this one. Let me know your thoughts.

**Comment by EAWF** [comment]
IMHO, there's not a lot of stars and watchers to be considered valuable, however, I see your point that we have time and momentum going, and sometimes that inertia is a good thing. 

The old-master idea is not a bad way to go.

My current thinking is that perhaps the focus of this repo might be better suited as a central point of tools and code to help users write paywalls, with branches for different programming languages.

If we do that, I can see that merging getBTC into here would be a good thing.
