### ISSUE TITLE
getBTCBalance returns NULL for addresses that have not been seen on the Blockchain

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#26]
Running the query for an address which has never been seen by the blockchain returns "[]".

It seems there are ~5 possible conditions at play:
* address has never been seen.
* address found in the mempool with funding.
* address found in the mempool, but has been spent (is this possible?)
* address found in a block with funding
* address found in a block, but has been spent (balance is 0)
Do I understand this correctly?

How can this be handled so as to report back to the calling program the current status of the address?

**Comment by Septem151** [comment]
I just ran a test using an address never seen before and it didn’t return `null`. It returned 0.00000000 as expected, since if the query returns no UTXOs it doesn’t iterate over anything, but still returns 0 because it’s returning `balance` variable which has been set to 0.

Can you provide an example of a test run you’ve done showing when `null` is returned?

**Comment by EAWF** [comment]
My mistake...it was when I ran the query from the command line that it produced the [].

I guess it only matters that the amount of 0 is returned in the long run.
