### ISSUE TITLE
Split getBTCRate into getBTCRate() & getBTCCoin($fiat)

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#48]
If you see me programming something that looks really cool and cute, and seems to work initially, please stop me!

I think it might be better to split this util into two separate functions:
- getBTCRate(): float - Returns the exchange rate from Bitstamp
  - Returns ###############.## (programmer can format further if needed)
- getBTCCoin( ######.## ): float - Returns number of bitcoin per USD input.
  - Returns ###########.########
Issue is having to deal with number formatting headaches and float errors for input and this way, they're kept separate, making operation, understanding, and documentation easier.

**Comment by Septem151** [comment]
> Issue is having to deal with number formatting headaches and float errors for input
Can you clarify and/or give an example of what you mean by this?

> ...this way, they're kept separate, making operation, understanding, and documentation easier.
I have a different perspective on this. I see a single function as being easier to understand and operate as opposed to having two different functions to remember the name and usage of. The only caveat to me is the name of the function itself, where `getBTCRate` makes perfect sense as the name for returning the Exchange Rate of USD/BTC, but is stretching the definition of the word "Rate" when applied to converting USD to BTC.

Currently, the function works as follows, and I can (and should) add some tests later on for this:
- Input to the function is missing: `getBTCRate()`
  - Returns the exchange amount
  - Rationale: as the name of the function implies, it gets the bitcoin exchange rate
- Input to the function is null: `getBTCRate(null)`
  - Returns the exchange amount, OR could return an error (up for debate on which we want to return)
  - Rationale: `null` isn't a valid USD amount, therefore is essentially ignored, OR an error is thrown because it's improper use of the function and we want to let the user know
- Input to the function is a string: `getBTCRate("this shouldn't be here")`
  - Returns an error, because of explicit type declaration of float for the value
  - Rationale: This is simply improper use of the function and we should let the user know that
- Input to the function is a positive integer: `getBTCRate(5)`
  - Returns the equivalent Bitcoin amount to the given USD amount
  - Rationale: You're getting the "Bitcoin Exchange Rate" for the amount of 5 USD, and integers can be autocasted to floats
- Input to the function is a positive float: `getBTCRate(2.99)`
  - Same as for positive integer
- Input to the function is a negative integer: `getBTCRate(-5)`
  - Returns the exchange amount, OR could return an error (up for debate on which we want to return)
  - Rationale: Could return exchange amount for reasons similar to passing null, since it's not a valid USD amount, OR could return an error because it's improper use of the function
- Input to the function is a negative float: `getBTCRate(-2.99)`
  - Same as for negative integer
- Input to the function is the value 0: `getBTCRate(0)`
  - Returns the bitcoin exchange rate
  - Rationale: Same as null case, 0 is not considered a valid USD amount and defaults to using the function as if no value was passed in
- Input to the function is some other object like an array: `getBTCRate([0, 3, 5])`
  - Returns an error, see the case for if input is a string

The need to separate this functionality into two functions seems arbitrary, and only complicates things for the implementer. Why separate something out into 2 functions when 1 function works fine for the use?

**Comment by EAWF** [comment]
Because I'm encountering problems with making sure the variable type is correct as I'm moving from one format to the other, and if I have problems now, just think about others who are less adept as I am.

**Comment by Septem151** [comment]
> Because I'm encountering problems with making sure the variable type is correct as I'm moving from one format to the other

I'm still not following, sorry... The function currently explicitly returns a string, is that what you're referring to? Because I noticed in your example at the top of this issue: `getBTCCoin( ######.## ): float` and `getBTCRate(): float`, that you want this function to be returning a numerical float value instead of a formatted number in the form of a string. If that's the case, it is easy to fix by changing the explicit return type from string to float. The only reason it is currently string in the first place is because originally, and currently, the exchange rate return value has a "$" appended to the beginning of the amount and also because you wanted the bitcoin value returned to always have a leading zero and 8 decimal points, which is only possible if the returned numerical value is a string.

As it stands at the moment, what I described above is what the function **currently does** with no changes required whatsoever.

**Comment by Septem151** [comment]
> I think a lot of my issues are adapting to being strict on variable typing. In the past, I never typed variables, just being sloppy and letting PHP take care of what it needed, when it needed it.

If necessary, we can remove the explicit return type and change the type based on the usage of getting the exchange rate vs the bitcoin/usd conversion. It makes sense to me for the return type to simply be float because the values we are returning are always going to be numbers. This way, formatting is the onus of the implementer as is usually the case for numerical values. It also does not lock them into one particular formatting style.

**Comment by EAWF** [comment]
Agree completely with that last.

The dollar signs and commas were my programming...which I need to remember to stop doing.  I get too slick for my britches sometimes.

**Comment by Septem151** [comment]
I'll make that change right now!

**Comment by EAWF** [comment]
I almost figured out the logic to building the bip-21 string...couldn't wrap my brain about how to deal with the URI ? and &'s and allow all the iterations of the variables.  Think I have it, but then I started encountering the float/string/formatting issues.

**Comment by EAWF** [comment]
Yes, everything that's a number in the project should probably be set as a float.

**Comment by EAWF** [comment]
To paraphrase what you said before, the onus of formatting should be on the programmer, not the developer

**Comment by Septem151** [comment]
I recommend you check out these resources for encoding URL query parameters:
- https://www.php.net/manual/en/function.http-build-query.php
- https://www.php.net/manual/en/function.urlencode.php

**Comment by EAWF** [comment]
Formats for BTC should be floats that are technically ############.########, IOW, largest integer it is, then a decimal point, then up to 8 decimals(I don't know when we'll have to deal with micro-satoshi's, but we should consider it going there.
Does that make sense?  No padded numbers except for the integer 0.xx  and allow the decimal points to fall where they may.
0.0001  0.001901. etc/

**Comment by EAWF** [comment]
Saw those, but here's my solution, which I think works...but I'm testing it.

function getBTCInvoice(string $account = 'Default', int $index = 0, float $amount = 0.00, string $label = "", string $message = ""): string {
  $address = getBTCAddress( $account , $index);
  $string = "";
  if ( !empty($message) ){ $string = $string."message=$message"; }
  if ( !empty($label) && !empty($string) ){ $string = "label=$label&".$string; } else { $string = "label=$label"; }
  if ( $amount > 0 && !empty($string) ){ $string = "amount=$amount&".$string; } else { $string = "amount=$amount"; }
  if ( !empty($string) ){ $string = "bitcoin:$address?".$string; } else { $string = "bitcoin:$address"; }
  $result = str_replace(" ","%20",$string);
  return $result;
  }

It's a bit compact right now, but that's easier for me to see what's going on without screwing things up with lots of empty space.

**Comment by EAWF** [comment]
I would think that leaving round out of the equation might be forward looking towards microsatoshi's. 
That's more of a decision for the programmer because they have to make the decision to lose money on rounding or not.

**Comment by Septem151** [comment]
> I would think that leaving round out of the equation might be forward looking towards microsatoshi's.
> That's more of a decision for the programmer because they have to make the decision to lose money on rounding or not.

Microsatoshis is not possible on the main chain and BIP-21 is not a Lightning network invoice.

**Comment by EAWF** [comment]
On the main chain, yet. Yeah, lightning is out of the scope of this project.  Version 2.0?  :smile:

**Comment by EAWF** [comment]
number_format() automatically rounds the numbers also.  Not documented in the manual.

**Comment by Septem151** [comment]
> On the main chain, yet.

I wouldn't get your hopes up on a "yet" :stuck_out_tongue: It would require changing how the satoshi value is stored in transactions which would be a hard fork and not backward compatible.

> number_format() automatically rounds the number also

Yes it does, but its return value is a string. round() function is specifically made to round floats and the return type is float.

**Comment by EAWF** [comment]
Good point...that means avoid using number_format in these functions?

**Comment by Septem151** [comment]
> Good point...that means avoid using number_format in these functions?

If you are working with the value in a numerical sense, yes. If you are using it to build a string, for example in the `getBTCInvoice` function, it would make sense to format it. However it's pointless to format the bitcoin amount in the URI because you'd be adding unnecessary bytes to be encoded in the QR code.

**Comment by EAWF** [comment]
Another good point about the btc amount.  Yeah, need it trimmed to bare minimum.

OK, well, it's working on my test cli platform now.  I'll post the updated functions as soon as I'm done testing them.

**Comment by EAWF** [comment]
Guess we can close this.
